services:
  - type: web
    name: wellnest-backend
    runtime: docker
    dockerfilePath: ./server/Dockerfile
    dockerContext: ./server
    envVars:
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: PORT
        value: 10000
      - key: CORS_ALLOWED_ORIGIN_PATTERNS
        sync: false
